exclude: [config.rb, shalinvs.tk.sublime-project, shalinvs.tk.sublime-workspace, nginx.conf, Rakefile, README.md]
markdown: rdiscount
pygments: true
permalink: /:title
rdiscount:
  extensions: [smart]